# Use wildcard "*" to expose all the endpoints
# Can also expose individual endpoints with a comma-delimited list
#By default, only '/health' is exposed. Hence, to expose '/info' we need to update properties as :
#management.endpoints.web.exposure.include = health,info -> Exposing endpoints individually using comma-delimited list
management.endpoints.web.exposure.include = * 
management.info.env.enabled = true 

# Exclude individual endpoints with a comma-delimited list as:
#management.endpoints.web.exposure.exclude = health,info

info.app.name = My Super cool app
info.app.description = A crazy fun app, yahooo!
info.app.version = 1.0.0

# Define the custom properties : The spring boot can access properties using @Value annotation
coach.name = Mickey Mouse
team.name = The Mickey Club
guest = W.W.White

# Configuring the Spring boot Server :
server.port = 7070 
# Now the http://localhost:8080 will be OFF (not respond) Instead http://localhost:7070 will be ACTIVE

# Set the context path of application
server.servlet.context-path = /mycoolapp
# Now, the http://localhost:7070 will give an HTTP 404 Error as we have set a context-path. So, the http://localhost:7070/mycoolapp will WORK and also for endpoints it must have request with prefix of context path as : http://localhost:7070/mycoolapp/greetGuest