spring.application.name=springcore

#To set the Lazy Initialization on global config i.e it will make all the classes as @Lazy annoted. Hence, No beans are created until needed including our DemoController
spring.main,lazy-initialization = true