spring.application.name=cruddemo

spring.datasource.url = jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username = springstudent
spring.datasource.password = springstudent

# To turn off the spring boot banner while running the application :
spring.main.banner-mode = off
# To reduce the logging level (so that it only shows warning and errors) :- Set the logging level to warn as -
logging.level.root = warn

# Add login configs to display SQL statements :
#1.To log the sql statements :
logging.level.org.hibernate.SQL=debug 
#2.To log the values for sql statements :
logging.level.org.hibernate.orm.jdbc.bind=trace

# Configure JPA/Hibernate to auto-create the tables
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
#following are the different modes:
#spring.jpa.hibernate.ddl-auto=PROPERTY-VALUE
#Property Values :
#1. none - No action will be performed
#2. create - Database tables are dropped followed by database tables creation
#3. create-drop -> Database tables are dropped followed by database tables creation.On application shutdown, drop the database table
#4. validate - Validate the database tables schema
#5. update - Update the database tables schema (keeps the previous data)
