#spring.application.name=mynewapp
#server.port = 8585

# Use wildcard "*" to expose all the endpoints
# Can also expose individual endpoints with a comma-delimited list
#By default, only '/health' is exposed. Hence, to expose '/info' we need to update properties as :
#management.endpoints.web.exposure.include = health,info -> Exposing endpoints individually using comma delimited list
management.endpoints.web.exposure.include = * 
management.info.env.enabled = true 
# after running the application now, we even get in terminal as : Exposing 2 endpoints beneath base path '/actuator'

info.app.name = My Super cool app
info.app.description = A crazy fun app, yahooo!
info.app.version = 1.0.0
info.app.color = white and black

#http://localhost:8080/actuator/threaddump -> This endpoint returns a JSON dump of all JVM threads currently running in your application
#http://localhost:8080/actuator/beans -> This endpoint returns every Spring Bean (objects) created inside the Application Context
#http://localhost:8080/actuator/mappings -> This endpoint returns the list of all the request mapping for your app and It is useful for finding out what request mappings are available
